foo:=bar
foo=>bar
foo<=bar
foo>=bar
foo<>bar
foo=bar
foo<bar
foo>bar
arrow->arrow-->arrow
arrow<-arrow<--arrow
arrow<->arrow<-->arrow
arrow==>arrow
arrow<==arrow
arrow<=>arrow<==>arrow

foo :=bar
foo =>bar
foo <=bar
foo >=bar
foo <>bar
foo =bar
foo <bar
foo >bar
arrow ->arrow -->arrow
arrow <-arrow <--arrow
arrow <->arrow <-->arrow
arrow ==>arrow
arrow <==arrow
arrow <=>arrow <==>arrow

foo:= bar
foo=> bar
foo<= bar
foo>= bar
foo<> bar
foo= bar
foo< bar
foo> bar
arrow-> arrow--> arrow
arrow<- arrow<-- arrow
arrow<-> arrow<--> arrow
arrow==> arrow
arrow<== arrow
arrow<=> arrow<==> arrow

foo := bar
foo => bar
foo <= bar
foo >= bar
foo <> bar
foo = bar
foo < bar
foo > bar
arrow -> arrow --> arrow
arrow <- arrow <-- arrow
arrow <-> arrow <--> arrow
arrow ==> arrow
arrow <== arrow
arrow <=> arrow <==> arrow
