foo:=bar
foo=>bar
foo<=bar
foo>=bar
foo<>bar
foo=bar
foo<bar
foo>bar
arrow->arrow-->arrow
arrow<-arrow<--arrow
arrow<->arrow<-->arrow
arrow==>arrow
arrow<==arrow
arrow<=>arrow<==>arrow
foo+bar
foo-bar
foo*bar
foo/bar
(* comment+comment-comment*comment/comment *)
'string+string-string*string/string'
'adjacent-string' adjacent-string 'adjacent-string'

foo :=bar
foo =>bar
foo <=bar
foo >=bar
foo <>bar
foo =bar
foo <bar
foo >bar
arrow ->arrow -->arrow
arrow <-arrow <--arrow
arrow <->arrow <-->arrow
arrow ==>arrow
arrow <==arrow
arrow <=>arrow <==>arrow
foo +bar
foo -bar
foo *bar
foo /bar
(* comment +comment -comment *comment /comment *)
'string +string -string *string /string'
'adjacent -string' adjacent -string 'adjacent -string'

foo:= bar
foo=> bar
foo<= bar
foo>= bar
foo<> bar
foo= bar
foo< bar
foo> bar
arrow-> arrow--> arrow
arrow<- arrow<-- arrow
arrow<-> arrow<--> arrow
arrow==> arrow
arrow<== arrow
arrow<=> arrow<==> arrow
foo+ bar
foo- bar
foo* bar
foo/ bar
(* comment+ comment- comment* comment/ comment *)
'string+ string- string* string/ string'
'adjacent- string' adjacent- string 'adjacent- string'

foo := bar
foo => bar
foo <= bar
foo >= bar
foo <> bar
foo = bar
foo < bar
foo > bar
arrow -> arrow --> arrow
arrow <- arrow <-- arrow
arrow <-> arrow <--> arrow
arrow ==> arrow
arrow <== arrow
arrow <=> arrow <==> arrow
foo + bar
foo - bar
foo * bar
foo / bar
(* comment + comment - comment * comment / comment *)
'string + string - string * string / string'
'adjacent - string' adjacent - string 'adjacent - string'

(* multi-line-
-comment *)
'multi-line-
-string'

DT#1995-09-06-00:00:00
-1
-1-2
-1-(-2)
1-2
-foo
-foo-bar
-foo-(-bar)
foo-bar
