-
 
--
  
----
   
----
    
    |

-
	
-	-
		
-	-	-
			
-	-	-	-
			
				|

---v--- max empty lines ---v---










---^--- max empty lines ---^---

foo
 bar 
  baz  
   foobar   
    foooo    

foo bar  baz   foobar    foooo    

foo
	bar	
		baz		
			foobar			
				foooo			

foo	bar		baz		foobar			foooo				

(foo)
 ( bar ) 
  (  baz  )  
   (   foo   bar   )   
    (    foo   baz    )    

[foo]
 [ bar ] 
  [  baz  ]  
   [   foo   bar   ]   
    [    foo   baz    ]    

(foo)
	(	bar	)	
		(		baz		)		
			(			foo			bar			)			
				(				foo			baz				)				

[foo]
	[	bar	]	
		[		baz		]		
			[			foo			bar			]			
				[				foo			baz				]				

foo; foo ; foo  ; foo   ; foo    ;
foo;	foo	;	foo		;	foo			;	foo				;
foo; foo	 ;	foo    		 ; foo				    	;