(* comment above *)
TYPE    struct:			(* type comment *)
		STRUCT					(* struct comment *)
foo				(* inline comment *)
	bar

		baz
			(* foobar *)
		END_STRUCT
END_TYPE

TYPE enum:(FOO:=1, BAR (* this is bar *),		(* this is *) SPARTA = 300 (* !!! *),fooo); END_TYPE

TYPE	enum		:	(* foo *)
		(				(* bar *)
foo,
	bar,
		baz:=3,

			(* hi *)
			);
END_TYPE
(* comment below *)

TYPE foo:
STRUCT
	bar: SomeSequence := 0, 42, 69;
END_STRUCT;
END_TYPE
