(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)

(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)
(* comment *)

(* nested comment in comment nested *)
before(* nested comment
across multi lines *)after

(* multi
line comment

with spaces
			and	tabs *)

(* test 1 variables *)

(* test 2 variables *)

(*
@SYSTEMCOMMENT
SOMESTUFF
*)
