name: Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-bash:
    name: Check shell code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1090,SC1091

  check-pwsh:
    name: Analyze PowerShell code
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\
          recurse: true
          output: results.sarif

  test-pwsh:
    name: Run PowerShell tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests for declaration checker
        shell: pwsh
        run: |
          .\tests\check-declarations\run.ps1
      - name: Run tests for code formatter
        shell: pwsh
        run: |
          .\tests\format-code\run.ps1
      - name: Run tests for tmp file remover
        shell: pwsh
        run: |
          .\tests\remove-tmp-files\pwsh\run.ps1

  test-bash:
    name: Run bash tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run tests for tmp file remover
        run: ./tests/remove-tmp-files/bash/run.sh
